// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjvmfrgmczproacrqaew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqdm1mcmdtY3pwcm9hY3JxYWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTU0OTUsImV4cCI6MjA3MjI3MTQ5NX0.5j6TTlswIPA_1PKRizYFmmGU_IrUb2prOsm0ouSrlF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});